spring:
  application:
    name: cart
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: localhost:6379

  kafka:
    bootstrap-servers: 34.71.194.186:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: cart
      auto-offset-reset: earliest




